services:
  wagtail:
    build:
      context: .
      dockerfile: Dockerfile.wagtail
    working_dir: /app/cplans
    volumes:
      - ./cplans:/app/cplans
      - ./entrypoint.sh:/entrypoint.sh
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://db_user:dbpassword@db:5432/db_cplans
    command: ["sh"]
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env.local

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: db_cplans
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:
